---
- name: Restart Server
  hosts: all
  become: true
  tasks:
    - name: list process
      shell:
        top -n1 -b
      register: top
    - name: proc
      debug:
        var:
          top.stdout_lines


