---
- name: Module C
  hosts: all
  become: true
  tasks:
    - name: Create File
      ansible.builtin.file:
        path: /var/foo.conf
        owner: dmitriy
        group: dmitriy
        mode: '777'