---
- name: Module C
  hosts: all
  become: true
  vars_files:
    - privvars.yml
  tasks:
        - name: Create File
          shell: |
             mkdir -p /home/test123
             touch /home/test123/test.txt
             echo 'testText' > /home/test123/test.123 
