---
- name: Module C
  hosts: all
  become: true
  tasks:
    - name: Create File
      shell: |
        mkdir -p /var/test123
        touch /var/test123/test.txt
        echo 'testText' > /var/test123/test.123